# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(414, 185)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 161, 111))
        self.label_utc = QLabel(self.groupBox)
        self.label_utc.setObjectName(u"label_utc")
        self.label_utc.setGeometry(QRect(10, 20, 81, 16))
        self.label_local = QLabel(self.groupBox)
        self.label_local.setObjectName(u"label_local")
        self.label_local.setGeometry(QRect(10, 60, 81, 16))
        self.label_show_utc = QLabel(self.groupBox)
        self.label_show_utc.setObjectName(u"label_show_utc")
        self.label_show_utc.setGeometry(QRect(10, 40, 141, 16))
        self.label_show_local = QLabel(self.groupBox)
        self.label_show_local.setObjectName(u"label_show_local")
        self.label_show_local.setGeometry(QRect(10, 80, 141, 16))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(180, 10, 221, 151))
        self.label_ip = QLabel(self.groupBox_2)
        self.label_ip.setObjectName(u"label_ip")
        self.label_ip.setGeometry(QRect(10, 20, 54, 12))
        self.label_port = QLabel(self.groupBox_2)
        self.label_port.setObjectName(u"label_port")
        self.label_port.setGeometry(QRect(10, 40, 54, 12))
        self.edit_bind_ip = QLineEdit(self.groupBox_2)
        self.edit_bind_ip.setObjectName(u"edit_bind_ip")
        self.edit_bind_ip.setEnabled(False)
        self.edit_bind_ip.setGeometry(QRect(70, 19, 141, 16))
        self.edit_bind_port = QLineEdit(self.groupBox_2)
        self.edit_bind_port.setObjectName(u"edit_bind_port")
        self.edit_bind_port.setEnabled(False)
        self.edit_bind_port.setGeometry(QRect(70, 40, 141, 16))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 60, 51, 21))
        self.edit_date_time = QDateTimeEdit(self.groupBox_2)
        self.edit_date_time.setObjectName(u"edit_date_time")
        self.edit_date_time.setGeometry(QRect(70, 60, 141, 21))
        self.btn_use_config = QPushButton(self.groupBox_2)
        self.btn_use_config.setObjectName(u"btn_use_config")
        self.btn_use_config.setGeometry(QRect(70, 110, 141, 31))
        self.btn_use_default = QPushButton(self.groupBox_2)
        self.btn_use_default.setObjectName(u"btn_use_default")
        self.btn_use_default.setGeometry(QRect(10, 110, 51, 31))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 90, 54, 12))
        self.comboBox = QComboBox(self.groupBox_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QRect(70, 85, 141, 21))
        self.comboBox.setEditable(False)
        self.label_info = QLabel(self.centralwidget)
        self.label_info.setObjectName(u"label_info")
        self.label_info.setGeometry(QRect(10, 130, 161, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.comboBox.setCurrentIndex(19)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"pyNTP", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c\u72b6\u6001", None))
        self.label_utc.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524dUTC \u65f6\u95f4\uff1a", None))
        self.label_local.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u672c\u5730\u65f6\u95f4\uff1a", None))
        self.label_show_utc.setText(QCoreApplication.translate("MainWindow", u"1970-01-01 00:00:00", None))
        self.label_show_local.setText(QCoreApplication.translate("MainWindow", u"1970-01-01 00:00:00", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.label_ip.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9aip  \uff1a", None))
        self.label_port.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u7aef\u53e3\uff1a", None))
        self.edit_bind_ip.setText(QCoreApplication.translate("MainWindow", u"0.0.0.0", None))
        self.edit_bind_port.setText(QCoreApplication.translate("MainWindow", u"123", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5b9a\u65f6\u95f4", None))
        self.edit_date_time.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy-MM-dd HH:mm:ss", None))
        self.btn_use_config.setText(QCoreApplication.translate("MainWindow", u"\u5e94\u7528\u914d\u7f6e\u542f\u52a8", None))
        self.btn_use_default.setText(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u672c\u5730\u65f6\u533a\uff1a", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"-11", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"-10", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"-9", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"-8", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"-7", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"-6", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"-5", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"-4", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"-3", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"-2", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"-1", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("MainWindow", u"+1", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("MainWindow", u"+2", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("MainWindow", u"+3", None))
        self.comboBox.setItemText(15, QCoreApplication.translate("MainWindow", u"+4", None))
        self.comboBox.setItemText(16, QCoreApplication.translate("MainWindow", u"+5", None))
        self.comboBox.setItemText(17, QCoreApplication.translate("MainWindow", u"+6", None))
        self.comboBox.setItemText(18, QCoreApplication.translate("MainWindow", u"+7", None))
        self.comboBox.setItemText(19, QCoreApplication.translate("MainWindow", u"+8", None))
        self.comboBox.setItemText(20, QCoreApplication.translate("MainWindow", u"+9", None))
        self.comboBox.setItemText(21, QCoreApplication.translate("MainWindow", u"+10", None))
        self.comboBox.setItemText(22, QCoreApplication.translate("MainWindow", u"+11", None))
        self.comboBox.setItemText(23, QCoreApplication.translate("MainWindow", u"+12", None))
        self.comboBox.setItemText(24, QCoreApplication.translate("MainWindow", u"+13", None))

        self.label_info.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\u4fe1\u606f", None))
    # retranslateUi

